// Headless artifact UI regression; native commands are strict, host-aware fixtures.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),os=require('node:os');
let playwright;try{playwright=require('playwright');}catch{playwright=require(path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
const ui=path.resolve(__dirname,'../../ui'),out=path.resolve(__dirname,'../../output/artifacts');
const fixture=fs.readFileSync(path.join(__dirname,'session-workspace.cjs'),'utf8').split('function bridgeFixture() {')[1].split('\nconst records = [];')[0];
const server=http.createServer((req,res)=>{const file=path.resolve(ui,'.'+new URL(req.url,'http://localhost').pathname);if(!file.startsWith(ui+path.sep))return res.writeHead(403).end();fs.readFile(file,(e,data)=>e?res.writeHead(404).end():res.end(data));});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await playwright.chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1400,height:900},reducedMotion:'reduce'});page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));fs.mkdirSync(out,{recursive:true});
 try{
  await page.route('**/bridge.js',route=>route.fulfill({contentType:'text/javascript',body:`(function bridgeFixture(){${fixture})();
   const original=window.jarvis;
   window.__artifactReads=[];window.__artifactWait={};window.__picker=[];
   window.jarvis=new Proxy(original,{get(target,name){
    if(name==='fileDialogState')return async active=>{window.__picker.push(active);return {ok:true};};
    if(name==='artifactNotes')return async(key,note,removeId)=>{if(window.__failNotes){window.__failNotes=false;return {ok:false,error:'Fixture note failure'};}let notes=JSON.parse(localStorage.getItem('fixture-notes:'+key)||'[]');if(removeId)notes=notes.filter(n=>n.id!==removeId);if(note){notes=notes.filter(n=>n.id!==note.id);notes.push(note);}localStorage.setItem('fixture-notes:'+key,JSON.stringify(notes));return {ok:true,notes};};
    if(name==='readArtifact')return async(sid,path)=>{window.__artifactReads.push([sid,path]);if(path==='/slow.txt')return new Promise(r=>window.__artifactWait.slow=r);if(path==='/missing.txt')return {ok:false,error:'Файл не найден на build-box'};const name=path.split('/').pop();let text=name.endsWith('.html')?'<h1>Макет страницы</h1><script>parent.__artifactEscaped=true</script>':name.endsWith('.docx')?'Текст документа':'# План запуска\\n\\nПроверить подключение и обработку ошибок.\\n\\nСледующий шаг — выпуск.';return {ok:true,name,type:name.endsWith('.html')?'text/html':'text/plain',converted:name.endsWith('.docx'),content:name.endsWith('.docx')?text:undefined,key:'fixture:'+path,dataBase64:btoa(unescape(encodeURIComponent(text)))};};
    return target[name];
   }});` }));
  await page.goto(`http://127.0.0.1:${server.address().port}/index.html`);await page.locator('#tabSessions').click();await page.locator('#newChatPrompt').waitFor();
  const chooserPromise=page.waitForEvent('filechooser');await page.locator('.sw-composer').getByRole('button',{name:'Прикрепить файл',exact:true}).click();const chooser=await chooserPromise;assert.equal(await page.evaluate(()=>window.__picker[0]),true);
  const svg='<svg xmlns="http://www.w3.org/2000/svg" width="640" height="420"><rect width="640" height="420" fill="#edf1f5"/><rect x="52" y="56" width="536" height="308" rx="20" fill="#fff"/><text x="84" y="120" font-size="27" fill="#243242">Project overview</text><rect x="84" y="157" width="170" height="130" rx="12" fill="#dce9f3"/><rect x="276" y="157" width="280" height="20" rx="6" fill="#dce2e9"/><rect x="276" y="196" width="216" height="16" rx="6" fill="#e8ecf1"/></svg>';
  await chooser.setFiles({name:'overview.svg',mimeType:'image/svg+xml',buffer:Buffer.from(svg)});await page.locator('.sw-attachment-preview').waitFor();await page.waitForFunction(()=>window.__picker.at(-1)===false);assert.equal(await page.locator('.sw-composer').isVisible(),true);
  await page.locator('.sw-attachment-preview').click();await page.locator('.artifact-image-stage img').waitFor();await page.waitForFunction(()=>!document.querySelector('.artifact-note-form button[type=submit]').disabled);assert.equal(await page.locator('.artifact-image-stage img').evaluate(i=>i.naturalWidth),640);
  await page.locator('.artifact-image-stage img').click({position:{x:110,y:90}});await page.getByRole('textbox',{name:'Комментарий к файлу'}).fill('Заголовок стоит выровнять с карточкой ниже.');await page.locator('.artifact-note-form button[type=submit]').click();await page.locator('.artifact-note').waitFor();assert.equal(await page.locator('.artifact-pin').count(),1);await page.screenshot({path:path.join(out,'image-notes-dark.png')});
  await page.locator('.artifact-close').click();await page.locator('.sw-attachment-preview').click();await page.locator('.artifact-note').waitFor();assert.match(await page.locator('.artifact-note').innerText(),/Заголовок/);
  await page.getByRole('button',{name:'Изменить',exact:true}).click();await page.getByRole('textbox',{name:'Комментарий к файлу'}).fill('Исправленный комментарий');await page.locator('.artifact-note-form button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('.artifact-note p').textContent==='Исправленный комментарий');
  await page.locator('.artifact-close').click();await page.locator('#sessionSidebar [data-session-id="build-box:remote-chat"]').click();await page.waitForFunction(()=>!document.getElementById('reply').disabled);
  await page.evaluate(()=>{for(const cb of window.__sessionFixture.events.onChatAppend||[])cb({sessionId:'build-box:remote-chat',items:[{role:'user',text:'Прочитай файл\nВложения (пути к файлам на машине агента):\n"/tmp/jarvis-attachment.fixture/report.docx"',ts:Date.now()}]});});
  await page.locator('#chatlog .attach').getByText('report.docx',{exact:true}).click();await page.locator('.artifact-text').waitFor();assert.deepEqual(await page.evaluate(()=>window.__artifactReads.at(-1)),['build-box:remote-chat','/tmp/jarvis-attachment.fixture/report.docx']);await page.keyboard.press('Escape');assert.equal(await page.locator('#artifactViewer').isVisible(),false);assert.equal(await page.locator('#chat').isVisible(),true);
  await page.evaluate(()=>{for(const cb of window.__sessionFixture.events.onChatAppend||[])cb({sessionId:'build-box:remote-chat',items:[{role:'assistant',text:'Готово: [План запуска](docs/plan.md) и [макет](preview.html).',ts:Date.now()}]});});
  await page.locator('#chatlog').getByRole('button',{name:'План запуска',exact:true}).click();await page.locator('.artifact-text h1').waitFor();assert.deepEqual(await page.evaluate(()=>window.__artifactReads.at(-1)),['build-box:remote-chat','docs/plan.md']);
  await page.locator('.artifact-text p').first().evaluate(p=>{const selection=getSelection(),r=document.createRange();r.selectNodeContents(p);selection.removeAllRanges();selection.addRange(r);p.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}));});
  assert.match(await page.locator('.artifact-anchor').innerText(),/Проверить/);
  await page.getByRole('textbox',{name:'Комментарий к файлу'}).fill('Добавь проверку повторного подключения.');await page.locator('.artifact-note-form button[type=submit]').click();await page.locator('.artifact-note blockquote').waitFor();await page.screenshot({path:path.join(out,'remote-markdown-notes.png')});
  await page.getByRole('button',{name:'В чат',exact:true}).click();assert.match(await page.locator('#reply').inputValue(),/Комментарий к файлу docs\/plan.md/);assert.match(await page.locator('#reply').inputValue(),/Добавь проверку/);
  await page.locator('#chatlog').getByRole('button',{name:'макет',exact:true}).click();await page.locator('.artifact-document').waitFor();assert.equal(await page.locator('.artifact-document').getAttribute('sandbox'),'');await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>window.__artifactEscaped),undefined);await page.getByRole('button',{name:'Исходник',exact:true}).click();assert.match(await page.locator('.artifact-text').innerText(),/<script>/);
  await page.evaluate(()=>{window.JarvisArtifacts.open({sessionId:'build-box:remote-chat',path:'/slow.txt'});});await page.locator('.artifact-preview .ui-skeleton').waitFor();await page.evaluate(()=>window.JarvisArtifacts.open({sessionId:'build-box:remote-chat',path:'/missing.txt'}));await page.getByText('Файл не найден на build-box',{exact:true}).waitFor();await page.evaluate(()=>window.__artifactWait.slow({ok:true,name:'wrong.txt',dataBase64:btoa('stale')}));assert.equal(await page.locator('.artifact-head strong').innerText(),'missing.txt');assert.equal(await page.locator('.artifact-text').count(),0);
  await page.evaluate(()=>window.JarvisArtifacts.open({sessionId:'build-box:remote-chat',path:'brief.docx'}));await page.locator('.artifact-text').waitFor();assert.match(await page.locator('.artifact-text').innerText(),/Текст документа/);
  const stream='BT /F1 24 Tf 54 720 Td (Artifact preview) Tj ET';
  const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`];
  let pdf='%PDF-1.4\n',offsets=[0];objects.forEach((o,i)=>{offsets.push(Buffer.byteLength(pdf));pdf+=`${i+1} 0 obj\n${o}\nendobj\n`;});const xref=Buffer.byteLength(pdf);pdf+=`xref\n0 6\n0000000000 65535 f \n`+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  await page.evaluate(dataUrl=>window.JarvisArtifacts.open({name:'brief.pdf',type:'application/pdf',dataUrl}), 'data:application/pdf;base64,'+Buffer.from(pdf).toString('base64'));
  await page.locator('.artifact-document').waitFor();assert.match(await page.locator('.artifact-document').getAttribute('src'),/^blob:/);await page.waitForTimeout(1000);await page.screenshot({path:path.join(out,'pdf-preview.png')});
  await page.evaluate(()=>{window.jarvisTheme.adopt({theme:'light',mode:'window'});return window.JarvisArtifacts.open({sessionId:'build-box:remote-chat',path:'docs/plan.md'});});await page.setViewportSize({width:600,height:850});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.join(out,'document-light-narrow.png')});
  await page.getByRole('textbox',{name:'Комментарий к файлу'}).fill('Черновик заметки');await page.locator('.artifact-close').click();await page.evaluate(()=>window.JarvisArtifacts.open({sessionId:'build-box:remote-chat',path:'docs/plan.md'}));assert.equal(await page.getByRole('textbox',{name:'Комментарий к файлу'}).inputValue(),'Черновик заметки');
  await page.evaluate(()=>{window.__failNotes=true;});await page.locator('.artifact-note-form button[type=submit]').click();await page.getByText('Fixture note failure',{exact:true}).waitFor();assert.equal(await page.getByRole('textbox',{name:'Комментарий к файлу'}).inputValue(),'Черновик заметки');
  assert.deepEqual(errors,[]);console.log(JSON.stringify({ok:true,checks:['picker focus guard and attachment appears','draft image preview','image point note','notes reopen/edit','remote host routing','agent file links','quote annotation','comment to chat draft','sandboxed HTML and source','stale reads ignored','read failure','Word text','light narrow layout','note draft retained','note save failure retains input','PDF inline preview','sent attachment preview from transcript','Escape keeps chat open'],errors}));
 }catch(error){console.log(await page.locator('#artifactViewer').innerText());console.log(errors);await page.screenshot({path:path.join(out,'failure.png')});throw error;}finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
