import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtemp, mkdir, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import test from 'node:test';

import { checkTauriAcl } from './check-tauri-acl.mjs';

const EXPECTED_CSP =
  "default-src 'self'; object-src 'none'; base-uri 'none'; frame-src 'none'; img-src 'self' data:; font-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self' ipc: http://ipc.localhost";
const TRUSTED_DOCUMENTS = new Map([
  ['main', ['index.html', './bridge.js']],
  ['toast', ['toast.html', './toast-bridge.js']],
  ['onboarding', ['onboarding.html', 'onboarding.js']],
  ['agent-chat', ['agent-chat.html', 'agent-chat.js']],
]);

async function writeJson(root, relative, value) {
  const destination = path.join(root, relative);
  await mkdir(path.dirname(destination), { recursive: true });
  await writeFile(destination, `${JSON.stringify(value, null, 2)}\n`);
}

async function safeFixture() {
  const root = await mkdtemp(path.join(tmpdir(), 'jarvis-tauri-acl-'));
  execFileSync('git', ['init', '--quiet'], { cwd: root });
  await writeFile(
    path.join(root, '.gitignore'),
    '/src-tauri/permissions/autogenerated/\n',
  );
  await writeFile(
    path.join(root, 'package.json'),
    `${JSON.stringify(
      {
        devDependencies: {
          '@tauri-apps/api': '2.11.1',
          esbuild: '0.25.12',
        },
      },
      null,
      2,
    )}\n`,
  );
  await mkdir(path.join(root, 'src-tauri/src'), { recursive: true });
  await writeFile(
    path.join(root, 'src-tauri/src/app_command_inventory.rs'),
    String.raw`macro_rules! with_app_commands {
  ($callback:ident) => {
    $callback! {
      ("state_get", crate::ipc::state_get, ["main"]),
    }
  };
}
`,
  );
  await writeJson(root, 'src-tauri/tauri.conf.json', {
    app: {
      withGlobalTauri: false,
      security: {
        freezePrototype: true,
        capabilities: ['main', 'toast', 'onboarding', 'agent-chat'],
        csp: EXPECTED_CSP,
      },
    },
  });
  await mkdir(path.join(root, 'ui'), { recursive: true });
  for (const [identifier, [filename, consumer]] of TRUSTED_DOCUMENTS) {
    const state =
      identifier === 'onboarding'
        ? '  <script src="onboarding-state.js"></script>\n'
        : '';
    const drag = ['onboarding', 'agent-chat'].includes(identifier)
      ? ' data-tauri-drag-region'
      : '';
    await writeFile(
      path.join(root, 'ui', filename),
      `<!doctype html>
<html><head>
  <meta http-equiv="Content-Security-Policy" content="${EXPECTED_CSP}" />
</head><body${drag}>
${state}  <script src="./generated/tauri-transport.js"></script>
  <script src="${consumer}"></script>
</body></html>
`,
    );
    await writeFile(
      path.join(root, 'ui', consumer.replace(/^\.\//, '')),
      "'use strict';\n",
    );
  }
  for (const identifier of ['main', 'toast', 'onboarding', 'agent-chat']) {
    await writeJson(root, `src-tauri/capabilities/${identifier}.json`, {
      identifier,
      local: true,
      webviews: [identifier],
      permissions: [
        'core:event:allow-listen',
        'core:event:allow-unlisten',
        ...(['main', 'toast'].includes(identifier)
          ? ['clipboard-manager:allow-write-text']
          : []),
        ...(['onboarding', 'agent-chat'].includes(identifier)
          ? ['core:window:allow-start-dragging']
          : []),
        ...(identifier === 'main' ? ['allow-state-get'] : []),
      ],
    });
  }
  return root;
}

async function expectCode(mutate, code) {
  const root = await safeFixture();
  await mutate(root);
  assert.throws(() => checkTauriAcl(root), (error) => {
    assert.equal(error.code, code);
    assert.match(error.message, new RegExp(code));
    return true;
  });
}

test('accepts the exact local trusted fixture', async () => {
  const root = await safeFixture();
  assert.deepEqual(checkTauriAcl(root), {
    commands: 1,
    capabilities: 4,
  });
});

test('rejects broad generated-permission ignores and handwritten ACL files', async () => {
  await expectCode(async (root) => {
    await writeFile(
      path.join(root, '.gitignore'),
      '/src-tauri/permissions/\n',
    );
  }, 'tauri_acl_generated_permission_ignore_invalid');

  await expectCode(async (root) => {
    await writeFile(path.join(root, '.gitignore'), '');
  }, 'tauri_acl_generated_permission_ignore_invalid');

  await expectCode(async (root) => {
    await writeFile(
      path.join(root, '.gitignore'),
      '/src-tauri/permissions/autogenerated/\n/src-tauri/\n',
    );
  }, 'tauri_acl_generated_permission_ignore_invalid');

  await expectCode(async (root) => {
    const permissions = path.join(root, 'src-tauri/permissions');
    await mkdir(permissions, { recursive: true });
    await writeFile(
      path.join(permissions, 'manual.toml'),
      '[[permission]]\nidentifier = "allow-bypass"\n',
    );
  }, 'tauri_acl_handwritten_permission_forbidden');

  await expectCode(async (root) => {
    const autogenerated = path.join(
      root,
      'src-tauri/permissions/autogenerated',
    );
    await mkdir(autogenerated, { recursive: true });
    await writeFile(
      path.join(autogenerated, 'state_get.toml'),
      '[[permission]]\nidentifier = "allow-bypass"\n',
    );
  }, 'tauri_acl_generated_permission_drift');
});

test('rejects window-wide capability scope with the stable error', async () => {
  await expectCode(async (root) => {
    const file = path.join(root, 'src-tauri/capabilities/main.json');
    const capability = JSON.parse(await (await import('node:fs/promises')).readFile(file));
    capability.windows = ['main'];
    delete capability.webviews;
    await writeJson(root, 'src-tauri/capabilities/main.json', capability);
  }, 'tauri_acl_window_scope_forbidden');
});

test('rejects remote and non-local capability parser bypasses', async () => {
  await expectCode(async (root) => {
    const file = path.join(root, 'src-tauri/capabilities/main.json');
    const capability = JSON.parse(await (await import('node:fs/promises')).readFile(file));
    capability.remote = null;
    await writeJson(root, 'src-tauri/capabilities/main.json', capability);
  }, 'tauri_acl_remote_scope_forbidden');

  await expectCode(async (root) => {
    const file = path.join(root, 'src-tauri/capabilities/main.json');
    const capability = JSON.parse(await (await import('node:fs/promises')).readFile(file));
    capability['remo\u0074e'] = { urls: ['https://example.invalid'] };
    await writeJson(root, 'src-tauri/capabilities/main.json', capability);
  }, 'tauri_acl_remote_scope_forbidden');

  for (const local of [false, 'true', null, 1]) {
    await expectCode(async (root) => {
      const file = path.join(root, 'src-tauri/capabilities/main.json');
      const capability = JSON.parse(await (await import('node:fs/promises')).readFile(file));
      capability.local = local;
      await writeJson(root, 'src-tauri/capabilities/main.json', capability);
    }, 'tauri_acl_local_scope_invalid');
  }

  await expectCode(async (root) => {
    const file = path.join(root, 'src-tauri/capabilities/main.json');
    const capability = JSON.parse(await (await import('node:fs/promises')).readFile(file));
    delete capability.local;
    await writeJson(root, 'src-tauri/capabilities/main.json', capability);
  }, 'tauri_acl_local_scope_invalid');
});

test('rejects wildcard and plugin-prefixed webview labels', async () => {
  await expectCode(async (root) => {
    await writeJson(root, 'src-tauri/capabilities/main.json', {
      identifier: 'main',
      local: true,
      webviews: ['*'],
      permissions: [
        'core:event:allow-listen',
        'core:event:allow-unlisten',
        'clipboard-manager:allow-write-text',
        'allow-state-get',
      ],
    });
  }, 'tauri_acl_webview_wildcard_forbidden');

  await expectCode(async (root) => {
    await writeJson(root, 'src-tauri/capabilities/main.json', {
      identifier: 'main',
      local: true,
      webviews: ['plugin-agent-vm'],
      permissions: [
        'core:event:allow-listen',
        'core:event:allow-unlisten',
        'clipboard-manager:allow-write-text',
        'allow-state-get',
      ],
    });
  }, 'tauri_acl_plugin_webview_forbidden');
});

test('rejects implicit capability and command grant drift', async () => {
  await expectCode(async (root) => {
    await writeJson(root, 'src-tauri/capabilities/extra.json', {
      identifier: 'extra',
      webviews: ['main'],
      permissions: [],
    });
  }, 'tauri_acl_unlisted_capability_forbidden');

  await expectCode(async (root) => {
    await writeJson(root, 'src-tauri/capabilities/main.json', {
      identifier: 'main',
      local: true,
      webviews: ['main'],
      permissions: [
        'core:event:allow-listen',
        'core:event:allow-unlisten',
        'clipboard-manager:allow-write-text',
      ],
    });
  }, 'tauri_acl_command_grant_drift');
});

test('derives exact support permissions from the trusted documents', async () => {
  await expectCode(async (root) => {
    const file = path.join(root, 'src-tauri/capabilities/main.json');
    const capability = JSON.parse(await (await import('node:fs/promises')).readFile(file));
    capability.permissions = capability.permissions.filter(
      (permission) => permission !== 'core:event:allow-unlisten',
    );
    await writeJson(root, 'src-tauri/capabilities/main.json', capability);
  }, 'tauri_acl_support_permission_drift');

  await expectCode(async (root) => {
    const file = path.join(root, 'src-tauri/capabilities/onboarding.json');
    const capability = JSON.parse(await (await import('node:fs/promises')).readFile(file));
    capability.permissions = capability.permissions.filter(
      (permission) => permission !== 'core:window:allow-start-dragging',
    );
    await writeJson(root, 'src-tauri/capabilities/onboarding.json', capability);
  }, 'tauri_acl_support_permission_drift');

  await expectCode(async (root) => {
    const file = path.join(root, 'src-tauri/capabilities/main.json');
    const capability = JSON.parse(await (await import('node:fs/promises')).readFile(file));
    capability.permissions.push('core:window:allow-start-dragging');
    await writeJson(root, 'src-tauri/capabilities/main.json', capability);
  }, 'tauri_acl_support_permission_drift');
});

test('rejects trusted HTML CSP, remote assets and bootstrap order drift', async () => {
  await expectCode(async (root) => {
    const file = path.join(root, 'ui/index.html');
    const html = await (await import('node:fs/promises')).readFile(file, 'utf8');
    await writeFile(
      file,
      html.replace("script-src 'self'", "script-src 'self' 'unsafe-inline'"),
    );
  }, 'tauri_acl_trusted_html_csp_invalid');

  await expectCode(async (root) => {
    const file = path.join(root, 'ui/onboarding.html');
    const html = await (await import('node:fs/promises')).readFile(file, 'utf8');
    await writeFile(
      file,
      html.replace(
        '</body>',
        "<ScRiPt SrC='//example.invalid/capture.js'></sCrIpT></body>",
      ),
    );
  }, 'tauri_acl_remote_asset_forbidden');

  await expectCode(async (root) => {
    const file = path.join(root, 'ui/toast.html');
    const html = await (await import('node:fs/promises')).readFile(file, 'utf8');
    await writeFile(
      file,
      html.replace(
        '  <script src="./toast-bridge.js"></script>',
        '  <script src="./interposed.js"></script>\n  <script src="./toast-bridge.js"></script>',
      ),
    );
  }, 'tauri_acl_transport_order_invalid');

  await expectCode(async (root) => {
    const file = path.join(root, 'ui/onboarding.html');
    const html = await (await import('node:fs/promises')).readFile(file, 'utf8');
    await writeFile(
      file,
      html.replace(
        '  <script src="onboarding-state.js"></script>\n',
        '',
      ).replace(
        '  <script src="onboarding.js"></script>',
        '  <script src="onboarding.js"></script>\n  <script src="onboarding-state.js"></script>',
      ),
    );
  }, 'tauri_acl_transport_order_invalid');
});

test('rejects execution-changing and malformed trusted script tags', async () => {
  const transport = './generated/tauri-transport.js';
  const consumer = './bridge.js';
  const attributes = [
    ' async',
    ' AsYnC="false"',
    ' defer',
    " DeFeR='defer'",
    ' type="module"',
    " TYPE='text/javascript'",
    ' nomodule',
    ' NoMoDuLe="false"',
    ' integrity="sha256-test"',
  ];

  for (const src of [transport, consumer]) {
    for (const attribute of attributes) {
      await expectCode(async (root) => {
        const file = path.join(root, 'ui/index.html');
        const html = await readFile(file, 'utf8');
        await writeFile(
          file,
          html.replace(
            `<script src="${src}">`,
            `<script src="${src}"${attribute}>`,
          ),
        );
      }, 'tauri_acl_script_tag_invalid');
    }

    for (const tag of [
      `<script src="${src}" SRC="${src}">`,
      `<script src=${src}>`,
      '<script src>',
      `<script src="${src}>`,
    ]) {
      await expectCode(async (root) => {
        const file = path.join(root, 'ui/index.html');
        const html = await readFile(file, 'utf8');
        await writeFile(file, html.replace(`<script src="${src}">`, tag));
      }, 'tauri_acl_script_tag_invalid');
    }
  }

  await expectCode(async (root) => {
    const file = path.join(root, 'ui/onboarding.html');
    const html = await readFile(file, 'utf8');
    await writeFile(
      file,
      html.replace(
        '<script src="onboarding-state.js">',
        '<script src="onboarding-state.js" defer>',
      ),
    );
  }, 'tauri_acl_script_tag_invalid');
});

test('rejects broad core permissions and unsafe Tauri config', async () => {
  await expectCode(async (root) => {
    await writeJson(root, 'src-tauri/capabilities/main.json', {
      identifier: 'main',
      local: true,
      webviews: ['main'],
      permissions: ['core:default', 'allow-state-get'],
    });
  }, 'tauri_acl_core_default_forbidden');

  await expectCode(async (root) => {
    const config = {
      app: {
        withGlobalTauri: true,
        security: {
          capabilities: ['main', 'toast', 'onboarding', 'agent-chat'],
          csp: "default-src 'self'",
        },
      },
    };
    await writeJson(root, 'src-tauri/tauri.conf.json', config);
  }, 'tauri_acl_global_tauri_forbidden');

  await expectCode(async (root) => {
    const config = {
      app: {
        withGlobalTauri: false,
        security: {
          capabilities: ['main', 'toast', 'onboarding', 'agent-chat'],
          csp: null,
        },
      },
    };
    await writeJson(root, 'src-tauri/tauri.conf.json', config);
  }, 'tauri_acl_csp_missing');
});

test('rejects unpinned trusted transport dependencies', async () => {
  await expectCode(async (root) => {
    await writeJson(root, 'package.json', {
      devDependencies: {
        '@tauri-apps/api': '^2.11.1',
        esbuild: '0.25.12',
      },
    });
  }, 'tauri_acl_dependency_pin_invalid');
});
