// Refresh the offline icon pack after updating @phosphor-icons/web.
// This copies only the regular WOFF2 font used by supported WebViews.
import { readFile, writeFile, copyFile, mkdir } from 'node:fs/promises';

const root = new URL('../', import.meta.url);
const source = new URL('node_modules/@phosphor-icons/web/', root);
const target = new URL('ui/vendor/phosphor/', root);
const { version } = JSON.parse(await readFile(new URL('package.json', source), 'utf8'));
const original = await readFile(new URL('src/regular/style.css', source), 'utf8');
const names = [...new Set([...original.matchAll(/\.ph\.ph-([a-z0-9-]+):before/g)].map(match => match[1]))].sort();
if (!names.length) throw new Error('The Phosphor stylesheet contains no recognized icons');

const aliases = {
  'alert-triangle': 'warning', 'triangle-alert': 'warning',
  settings: 'gear-six', mic: 'microphone', 'mic-off': 'microphone-slash',
  'volume-2': 'speaker-high', 'volume-x': 'speaker-slash',
  cable: 'plugs-connected', server: 'hard-drives', terminal: 'terminal-window',
  'chevron-down': 'caret-down', 'chevron-up': 'caret-up',
  'chevron-left': 'caret-left', 'chevron-right': 'caret-right',
  'rotate-ccw': 'arrow-counter-clockwise', 'rotate-cw': 'arrow-clockwise',
  'refresh-cw': 'arrows-clockwise', search: 'magnifying-glass',
  'loader-circle': 'spinner-gap', 'trash-2': 'trash',
  history: 'clock-counter-clockwise', insights: 'chart-bar', dict: 'book-open-text',
  scratch: 'notepad', git: 'git-branch', text: 'text-t', lang: 'translate',
  'message-square': 'chat-text', 'message-circle': 'chat-circle',
  'messages-square': 'chats', 'folder-closed': 'folder',
  'external-link': 'arrow-square-out', 'arrow-up-right': 'arrow-up-right',
  'arrow-left': 'arrow-left', 'arrow-right': 'arrow-right',
  'chevrons-up-down': 'caret-up-down', 'more-horizontal': 'dots-three',
  'more-vertical': 'dots-three-vertical', 'plus-circle': 'plus-circle',
  'check-circle': 'check-circle', 'circle-check': 'check-circle',
  'x-circle': 'x-circle', 'circle-x': 'x-circle',
  'panel-left': 'sidebar-simple', 'layout-dashboard': 'squares-four',
  'bar-chart-3': 'chart-bar', 'file-text': 'file-text',
  'square-pen': 'note-pencil', 'square-terminal': 'terminal-window',
  'headphones': 'headphones', 'audio-lines': 'waveform',
  'circle-help': 'question', 'help-circle': 'question',
  'link-2': 'link', 'unlink-2': 'link-break', 'circle-stop': 'stop-circle',
  'maximize-2': 'arrows-out-simple', 'minimize-2': 'arrows-in-simple',
  'shield-check': 'shield-check', 'log-out': 'sign-out', 'log-in': 'sign-in',
};
for (const [alias, name] of Object.entries(aliases)) {
  if (!names.includes(name)) throw new Error(`Unknown Phosphor mapping: ${alias} → ${name}`);
}
if (!names.includes('circle-dashed')) throw new Error('The fallback icon is missing');

await mkdir(target, { recursive: true });
await copyFile(new URL('src/regular/Phosphor.woff2', source), new URL('Phosphor.woff2', target));
await copyFile(new URL('LICENSE', source), new URL('LICENSE', target));
const css = original.replace(/src:[\s\S]*?;/, 'src: url("./Phosphor.woff2") format("woff2");');
await writeFile(new URL('style.css', target), `/* @phosphor-icons/web ${version}; MIT. Generated by scripts/sync-icons.mjs. */\n${css}\n.ph { display: inline-block; flex: none; width: 1em; height: 1em; font-size: var(--icon-size, 18px); vertical-align: -.125em; }\n`);

const runtime = `/* Generated from @phosphor-icons/web ${version} by scripts/sync-icons.mjs.
 * Local, decorative icons. Unknown names resolve to a visible fallback. */
(() => {
  'use strict';
  const names = new Set(${JSON.stringify(names.join(' '))}.split(' '));
  const aliases = Object.freeze(${JSON.stringify(aliases, null, 2)});
  function resolve(name) {
    const key = String(name || '').trim().toLowerCase().replace(/^ph-/, '');
    const mapped = Object.prototype.hasOwnProperty.call(aliases, key) ? aliases[key] : key;
    return names.has(mapped) ? mapped : 'circle-dashed';
  }
  function create(name, size) {
    const icon = document.createElement('i');
    const resolved = resolve(name);
    icon.className = 'ph ph-' + resolved;
    icon.setAttribute('aria-hidden', 'true');
    icon.setAttribute('data-icon', resolved);
    if (typeof size === 'number' && Number.isFinite(size) && size > 0 && size <= 512) {
      icon.style.setProperty('--icon-size', size + 'px');
    }
    return icon;
  }
  window.jarvisIcons = Object.freeze({ create, resolve });
})();
`;
await writeFile(new URL('ui/icons.js', root), runtime);
console.log(`Synced Phosphor ${version}: ${names.length} regular icons, one offline WOFF2 font`);
