//! Single source of truth for app-command registration and trusted-webview ACLs.
//!
//! The callback macro is intentionally consumable from both `main.rs` and
//! `build.rs`: runtime uses the handler path, while the build script uses the
//! stable wire name to generate Tauri permissions. The webview labels are
//! enforced by `tests/app_command_acl.rs` and `scripts/check-tauri-acl.mjs`.

macro_rules! with_app_commands {
    ($callback:ident) => {
        $callback! {
            ("state_get", crate::ipc::state_get, ["main"]),
            ("state_clear", crate::ipc::state_clear, ["main"]),
            ("panel_hide", crate::ipc::panel_hide, ["main"]),
            ("settings_get", crate::ipc::settings_get, ["main"]),
            ("settings_set", crate::ipc::settings_set, ["main"]),
            ("settings_health", crate::ipc::settings_health, ["main"]),
            ("settings_repair", crate::ipc::settings_repair, ["main", "onboarding"]),
            ("chat_open", crate::ipc::chat_open, ["main"]),
            ("chat_summarize", crate::ipc::chat_summarize, ["main"]),
            ("file_open", crate::ipc::file_open, ["main"]),
            ("file_read", crate::ipc::file_read, ["main"]),
            ("file_diff", crate::ipc::file_diff, ["main"]),
            ("agent_vm_file_open", crate::ipc::agent_vm_file_open, ["main"]),
            ("agent_vm_file_read", crate::ipc::agent_vm_file_read, ["main"]),
            ("agent_vm_file_diff", crate::ipc::agent_vm_file_diff, ["main"]),
            ("url_open", crate::ipc::url_open, ["main"]),
            ("chat_close", crate::ipc::chat_close, ["main"]),
            ("commands_get", crate::ipc::commands_get, ["main"]),
            ("app_meta", crate::ipc::app_meta, ["main"]),
            ("update_check_install", crate::ipc::update_check_install, ["main"]),
            ("app_relaunch", crate::ipc::app_relaunch, ["main", "onboarding"]),
            ("plugins_status", crate::ipc::plugins_status, ["main"]),
            ("plugins_cmd", crate::ipc::plugins_cmd, ["main"]),
            ("entities_get", crate::ipc::entities_get, ["main"]),
            ("agent_vm_profiles_get", crate::ipc::agent_vm_profiles_get, ["main"]),
            ("agent_vm_profile_set", crate::ipc::agent_vm_profile_set, ["main"]),
            ("project_manager_state_get", crate::ipc::project_manager_state_get, ["main"]),
            ("project_manager_folder_pick", crate::ipc::project_manager_folder_pick, ["main"]),
            ("project_manager_favorite_set", crate::ipc::project_manager_favorite_set, ["main"]),
            ("project_manager_favorite_move", crate::ipc::project_manager_favorite_move, ["main"]),
            ("project_manager_view_set", crate::ipc::project_manager_view_set, ["main"]),
            ("agent_vm_focus", crate::ipc::agent_vm_focus, ["main"]),
            ("agent_vm_operation_ack", crate::ipc::agent_vm_operation_ack, ["main"]),
            ("agent_vm_commands_get", crate::ipc::agent_vm_commands_get, ["main"]),
            ("agent_vm_terminal_ensure", crate::ipc::agent_vm_terminal_ensure, ["main"]),
            ("agent_vm_terminal_snapshot", crate::ipc::agent_vm_terminal_snapshot, ["main"]),
            ("agent_vm_terminal_input", crate::ipc::agent_vm_terminal_input, ["main"]),
            ("agent_vm_terminal_key", crate::ipc::agent_vm_terminal_key, ["main"]),
            ("agent_vm_terminal_upload", crate::ipc::agent_vm_terminal_upload, ["main"]),
            ("agent_vm_terminal_resize", crate::ipc::agent_vm_terminal_resize, ["main"]),
            ("agent_vm_terminal_stop", crate::ipc::agent_vm_terminal_stop, ["main"]),
            ("usage_summary", crate::ipc::usage_summary, ["main"]),
            ("limit_get", crate::ipc::limit_get, ["main"]),
            ("history_get", crate::ipc::history_get, ["main"]),
            ("usage_session", crate::ipc::usage_session, ["main"]),
            ("session_set_pin", crate::ipc::session_set_pin, ["main"]),
            ("session_set_model", crate::ipc::session_set_model, ["main"]),
            ("session_set_effort", crate::ipc::session_set_effort, ["main"]),
            ("terminal_ping", crate::ipc::terminal_ping, ["main"]),
            ("question_answer", crate::ipc::question_answer, ["main", "toast"]),
            ("task_action", crate::ipc::task_action, ["main"]),
            ("voice_get", crate::ipc::voice_get, ["main"]),
            ("voice_set_speaker", crate::ipc::voice_set_speaker, ["main"]),
            ("voice_set_rate", crate::ipc::voice_set_rate, ["main"]),
            ("voice_test", crate::ipc::voice_test, ["main"]),
            ("voice_set_mute", crate::ipc::voice_set_mute, ["main"]),
            ("voice_set_duck", crate::ipc::voice_set_duck, ["main"]),
            ("voice_set_bluetooth_only", crate::ipc::voice_set_bluetooth_only, ["main"]),
            ("session_reply", crate::ipc::session_reply, ["main"]),
            ("session_save_image", crate::ipc::session_save_image, ["main"]),
            ("session_continue", crate::ipc::session_continue, ["toast"]),
            ("agent_confirm", crate::ipc::agent_confirm, ["agent-chat"]),
            ("voice_pick_resolve", crate::ipc::voice_pick_resolve, ["toast"]),
            ("voice_stage_cancel", crate::ipc::voice_stage_cancel, ["toast"]),
            ("voice_audio_state", crate::ipc::voice_audio_state, ["toast"]),
            ("voice_confirm_resolve", crate::ipc::voice_confirm_resolve, ["toast"]),
            ("voice_abort", crate::ipc::voice_abort, ["toast"]),
            ("agent_chat_open", crate::ipc::agent_chat_open, []),
            ("terminal_focus", crate::ipc::terminal_focus, ["main"]),
            ("session_launch", crate::ipc::session_launch, ["main"]),
            ("toast_resize", crate::ipc::toast_resize, ["toast"]),
            ("toast_ready", crate::ipc::toast_ready, ["toast"]),
            ("toast_click", crate::ipc::toast_click, ["toast"]),
            ("onboarding_status", crate::onboarding::onboarding_status, []),
            ("onboarding_get", crate::onboarding::onboarding_get, ["onboarding"]),
            ("onboarding_run", crate::onboarding::onboarding_run, ["onboarding"]),
            ("onboarding_open", crate::onboarding::onboarding_open, ["main"]),
            ("onboarding_close", crate::onboarding::onboarding_close, ["onboarding"]),
            ("onboarding_open_panel", crate::onboarding::onboarding_open_panel, ["onboarding"]),
            ("onboarding_open_settings", crate::onboarding::onboarding_open_settings, ["onboarding"]),
            ("integration_get", crate::onboarding::integration_get, ["main"]),
            ("integration_remove", crate::onboarding::integration_remove, ["main"]),
            ("model_delete", crate::onboarding::model_delete, ["main"]),
            ("quiet_set", crate::onboarding::quiet_set, ["main"]),
            ("agent_send", crate::ipc::agent_send, ["agent-chat"]),
            ("stt_get", crate::ipc::stt_get, ["main"]),
            ("models_get", crate::ipc::models_get, ["main"]),
            ("transcripts_get", crate::ipc::transcripts_get, ["main"]),
            ("transcripts_clear", crate::ipc::transcripts_clear, ["main"]),
            ("transcript_delete", crate::ipc::transcript_delete, ["main"]),
            ("transcript_retranscribe", crate::ipc::transcript_retranscribe, ["main"]),
            ("transcript_enhance", crate::ipc::transcript_enhance, ["main"]),
            ("prompts_get_settings", crate::ipc::prompts_get_settings, ["main"]),
            ("prompts_set_smart", crate::ipc::prompts_set_smart, ["main"]),
            ("prompts_get", crate::ipc::prompts_get, ["main"]),
            ("stt_set_engine", crate::ipc::stt_set_engine, ["main"]),
            ("stt_set_hotkey", crate::ipc::stt_set_hotkey, ["main"]),
            ("hotkey_bindings", crate::ipc::hotkey_bindings, ["main"]),
            ("hotkey_assign", crate::ipc::hotkey_assign, ["main"]),
            ("hotkeys_suspend", crate::ipc::hotkeys_suspend, ["main"]),
            ("stt_set_noise_gate", crate::ipc::stt_set_noise_gate, ["main"]),
            ("stt_test", crate::ipc::stt_test, ["main"]),
            ("voice_history_open", crate::ipc::voice_history_open, ["toast"]),
            ("stt_input_devices", crate::ipc::stt_input_devices, ["main"]),
            ("stt_set_input_device", crate::ipc::stt_set_input_device, ["main"]),
            ("service_get", crate::ipc::service_get, ["main"]),
            ("service_set_backend", crate::ipc::service_set_backend, ["main"]),
            ("service_set_model", crate::ipc::service_set_model, ["main"]),
            ("service_set_effort", crate::ipc::service_set_effort, ["main"]),
            ("service_set_proxy", crate::ipc::service_set_proxy, ["main"]),
            ("service_test", crate::ipc::service_test, ["main"]),
            ("claude_auth_get", crate::ipc::claude_auth_get, ["main"]),
            ("claude_auth_connect", crate::ipc::claude_auth_connect, ["main"]),
            ("claude_auth_disconnect", crate::ipc::claude_auth_disconnect, ["main"]),
            ("codex_install_sidecar", crate::onboarding::codex_install_sidecar, ["main"]),
            ("stt_install_whisper", crate::onboarding::stt_install_whisper, ["main"]),
            ("stt_install_sidecar", crate::onboarding::stt_install_sidecar, ["main"]),
            ("stt_install_qwen", crate::onboarding::stt_install_qwen, ["main"]),
            ("wake_get", crate::ipc::wake_get, ["main"]),
            ("wake_set_enabled", crate::ipc::wake_set_enabled, ["main"]),
            ("wake_set_threshold", crate::ipc::wake_set_threshold, ["main"]),
            ("audio_set_mute", crate::ipc::audio_set_mute, ["main"]),
            ("wake_install_models", crate::onboarding::wake_install_models, ["main"]),
            ("voice_install_silero", crate::onboarding::voice_install_silero, ["main"]),
            ("models_install", crate::onboarding::models_install, ["main", "onboarding"]),
        }
    };
}

pub(crate) use with_app_commands;
